USERNAME_MAKER_CASHFLOW_BLOTTER = "maker|password"
PASSWORD_MAKER_CASHFLOW_BLOTTER = "password"
USERNAME_CHECKER_CASHFLOW_BLOTTER = "checker|password"
PASSWORD_CHECKER_CASHFLOW_BLOTTER = "password"
WAIT_CF_STATUS_LOOP_TIME = 1
QUERY_RESULT = "$.data.graphCashFlowDetails[0]"

SettlementMthod_CCIL = "CCIL"
SettlementMthod_Cash = "Cash"
SubStatType_PendingAutoNetting = "Pending Auto Netting"
SubStatType_PendingException = "Pending Exception"
SubStatTypeSuppress_CashflowSuppression = "Cashflow Suppression"
excpCategory_OTHER = "OTHER"
Pay = "Pay"
Receive = "Receive"
State_SWIFT_SUPPRESSED = "SWIFT_SUPPRESSED"

jPathInCfDetails_cfSubStat = "$.data.graphCashFlowDetails[0].cashflow.Cashflow.Cashflow_Sub_State"
jPathInCfDetails_cfStat = "$.data.graphCashFlowDetails[0].cashflow.Cashflow.Cashflow_State"
jPathInCfDetails_cfSubStatType = "$.data.graphCashFlowDetails[0].cashflow.Cashflow.Cashflow_Sub_State_Type"
jPathInCfDetails_SettlementMethod = "$.data.graphCashFlowDetails[0].cashflow.Settlement_Method"
jPathInCfDetails_Amount = "$.data.graphCashFlowDetails[0].cashflow.Cashflow.Payment_Amount"
jPathInCfDetails_PayReceiveIndicator = "$.data.graphCashFlowDetails[0].cashflow.Cashflow.Pay_Receive_Indicator"
jPathInCfDetails_CounterpartyFMID = "$.data.graphCashFlowDetails[0].cashflow.Entity.Counterparty_SCI_FMID"
jPathInCfDetails_CounterpartyFMCode = "$.data.graphCashFlowDetails[0].cashflow.Entity.Counterparty_SCI_FMCODE"
jPathInCfDetails_nettingId = "$.data.graphCashFlowDetails[0].cashflow.Cashflow.Netting_Id"
jPathInCfDetails_CFICode = "$.data.graphCashFlowDetails[0].cashflow.Instrument_Common.CFI_Code"
jPathInCfDetails_Taxonomy = "$.data.graphCashFlowDetails[0].cashflow.Instrument_Common.ISDA_Taxonomy"
jPathInCfDetails_PaymentType = "$.data.graphCashFlowDetails[0].cashflow.Cashflow.Payment_Type"
jPathInCfDetails_PaymentDate = "$.data.graphCashFlowDetails[0].cashflow.Cashflow.Payment_Date"
excpInCfDetails_NetCashflow = "$.data.graphCashFlowDetails[0].cashflow.ratanException[?(@.Exception_Code==\"Net Cashflow\")].Exception_Category"
jPathInQuickSearchResult_prefix = "$.data.cashflowUltraQuery.results"
CN_SENT_TO_LMS_TOPIC = "CN_SENT_TO_LMS_TOPIC"
stackVaule_Ratan_lifecycle = "stackValue"
stackVaule_LMS_kafkaMsg = "stackValue"

StellaUber_InterestRate_CrossCurrency_FixedFloat_FloatLeg = "StellaUber_InterestRate_CrossCurrency_FixedFloat_FloatLeg"
StellaUber_InterestRate_CrossCurrency_FixedFloat_FloatLeg_Withdraw = "StellaUber_InterestRate_CrossCurrency_FixedFloat_FloatLeg_Withdraw"